export const items = {
  'item-1': {
    id: 'item-1',
    name: 'Chicken Pan',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-morning', name: 'morning', label: 'Morning'},
    par: { applyDaily: true, default: 5 },
    made: 3, 
    onHand: {beg: 3, end:5}, 
    comments: 'Be sure to marinate all chickens for this week',
    createdDate: '11/23/18', 
  },
  'item-2': {
    id: 'item-2',
    name: 'Salmon Pan',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-morning', name: 'morning', label: 'Morning'},
    par: { applyDaily: true, default: 9 },
    made: 2, 
    onHand: {beg: 6, end:5}, 
    comments: 'Be sure to marinate all salmons for this week',
    createdDate: '11/23/18', 
  },
  'item-3': {
    id: 'item-3',
    name: 'Beef',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-morning', name: 'morning', label: 'Morning'},
    par: { applyDaily: true, default: 5 },
    made: 3, 
    onHand: {beg: 3, end:5}, 
    comments: 'Be sure to marinate all chickens for this week',
    createdDate: '11/23/18', 
  },
  'item-4': {
    id: 'item-4',
    name: 'Seaweed cup',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 5 },
    made: 3, 
    onHand: {beg: 3, end:5}, 
    comments: 'Be sure to marinate all chickens for this week',
    createdDate: '11/23/18', 
  },
  'item-5': {
    id: 'item-5',
    name: 'Kimchi',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 6 },
    made: 2, 
    onHand: {beg: 4, end:6}, 
    comments: 'Be sure to marinate all Kimchis for this week',
    createdDate: '11/23/18', 
  },
  'item-6': {
    id: 'item-6',
    name: 'Jalapeno pint',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-2', label: 'Sauces', name: 'sauces'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 6 },
    made: 2, 
    onHand: {beg: 4, end:6}, 
    comments: 'Make it good',
    createdDate: '11/23/18', 
  },   
  'item-7': {
    id: 'item-7',
    name: 'Chipotle',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-2', label: 'Sauces', name: 'sauces'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 6 },
    made: 4, 
    onHand: {beg: 2, end: 3}, 
    comments: 'Make it good',
    createdDate: '11/23/18', 
  },
  'item-8':  {
    id: 'item-8',
    name: 'Wasabi',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-2', label: 'Sauces', name: 'sauces'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 3 },
    made: 1, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18', 
  },
  'item-9':  {
    id: 'item-9',
    name: 'Shrimp',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-dinner', name: 'dinner', label: 'Dinner'},
    par: { applyDaily: true, default: 10 },
    made: 2, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18', 
  }, 
  'item-10': {
    id: 'item-10',
    name: 'Dish Wash',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: false,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-dinner', name: 'dinner', label: 'Dinner'},
    par: { applyDaily: true, default: 10 },
    made: 2, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18',     
  },
  'item-11': {
    id: 'item-11',
    name: 'Fried Rice',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-unassigned', name: 'unassigned', label: 'Unassigned'},
    timeFrame: { id: 'time-unassigned', name: 'unassigned', label: 'Unassigned'},
    par: { applyDaily: true, default: 10 },
    made: 2, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18',     
  },   
}

const stations = {
  'station-1': { 
    id: 'station-1',
    name: 'kitchen-prep',
    label: 'Kitchen Prep',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    createdTime: '05/16/2019',
    itemIds: ['item-1', 'item-2', 'item-3', 'item-4', 'item-5',  'item-6']
  },
  'station-2': {
    id: 'station-2',
    name: 'sauces',
    label: 'Sauces',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    createdTime: '05/16/2019',
    itemIds: ['item-7', 'item-8', 'item-9']
  },
  'station-unassigned': {
    id: 'station-unassigned',
    name: 'unassigned',
    label: 'Unassigned',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    createdTime: '05/16/2019',
    itemIds: ['item-10', 'item-11']    
  }
};

const timeFrames = {
  'time-morning': {
    id: 'time-morning',
    name: 'morning',
    label: 'Morning',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    createdTime: '05/16/2019',
    itemIds: ['item-1', 'item-2', 'item-3']
  },
  'time-afternoon': {
    id: 'time-afternoon',
    name: 'afternoon',
    label: 'Afternoon',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    createdTime: '05/16/2019',
    itemIds: ['item-4', 'item-5', 'item-6', 'item-7','item-8']
  },
  'time-dinner': {
    id: 'time-dinner',
    name: 'dinner',
    label: 'Dinner',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    createdTime: '05/16/2019',
    itemIds: ['item-9', 'item-10']
  },
  'time-unassigned': {
    id: 'time-unassigned',
    name: 'unassigned',
    label: 'Unassigned',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    createdTime: '05/16/2019',
    itemIds: ['item-11']
  }
}

const all = {
  'all': {
    id: 'all',
    name: 'all',
    label: 'All',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    createdTime: '05/16/2019',
    itemIds: ['item-1', 'item-2', 'item-3', 'item-4', 'item-5','item-6', 'item-7', 'item-8', 'item-9', 'item-10', 'item-11']
  },
}

export const sortedItems = {
  items: items, 
  id: 'sortedItem-1',
  date: new Date(),
  location: { id: '1', name: 'albany', label:'Albany' },
  published: false,
  publishTime: null, 
  stationsOrder: ['station-1', 'station-2', 'station-unassigned'],
  timeFrameOrder: ['time-morning', 'time-afternoon', 'time-dinner', 'time-unassigned'],
  allOrder: ['all'],
  stations: stations,
  timeFrames: timeFrames,
  all: all
};


export const allItems = [
  {
    id: 'item-1',
    name: 'Chicken Pan',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-morning', name: 'morning', label: 'Morning'},
    par: { applyDaily: true, default: 5 },
    made: 3, 
    onHand: {beg: 3, end:5}, 
    comments: 'Be sure to marinate all chickens for this week',
    createdDate: '11/23/18', 
  },
  {
    id: 'item-2',
    name: 'Salmon Pan',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-morning', name: 'morning', label: 'Morning'},
    par: { applyDaily: true, default: 9 },
    made: 2, 
    onHand: {beg: 6, end:5}, 
    comments: 'Be sure to marinate all salmons for this week',
    createdDate: '11/23/18', 
  }, 
  {
    id: 'item-3',
    name: 'Beef',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-morning', name: 'morning', label: 'Morning'},
    par: { applyDaily: true, default: 5 },
    made: 3, 
    onHand: {beg: 3, end:5}, 
    comments: 'Be sure to marinate all chickens for this week',
    createdDate: '11/23/18', 
  },
  {
    id: 'item-4',
    name: 'Seaweed cup',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 5 },
    made: 3, 
    onHand: {beg: 3, end:5}, 
    comments: 'Be sure to marinate all chickens for this week',
    createdDate: '11/23/18', 
  },
  {
    id: 'item-5',
    name: 'Kimchi',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 6 },
    made: 2, 
    onHand: {beg: 4, end:6}, 
    comments: 'Be sure to marinate all Kimchis for this week',
    createdDate: '11/23/18', 
  },         
  {
    id: 'item-6',
    name: 'Jalapeno pint',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-2', label: 'Sauces', name: 'sauces'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 6 },
    made: 2, 
    onHand: {beg: 4, end:6}, 
    comments: 'Make it good',
    createdDate: '11/23/18', 
  },
  {
    id: 'item-7',
    name: 'Chipotle',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-2', label: 'Sauces', name: 'sauces'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 6 },
    made: 4, 
    onHand: {beg: 2, end: 3}, 
    comments: 'Make it good',
    createdDate: '11/23/18', 
  },
  {
    id: 'item-8',
    name: 'Wasabi',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-2', label: 'Sauces', name: 'sauces'},
    timeFrame: { id: 'time-afternoon', name: 'afternoon', label: 'Afternoon'},
    par: { applyDaily: true, default: 3 },
    made: 1, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18', 
  },
  {
    id: 'item-9',
    name: 'Shrimp',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-dinner', name: 'dinner', label: 'Dinner'},
    par: { applyDaily: true, default: 10 },
    made: 2, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18', 
  }, 
  {
    id: 'item-10',
    name: 'Dish Wash',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: false,
    station: { id: 'station-1', label: 'Kitchen Prep', name: 'kitchen-prep'},
    timeFrame: { id: 'time-dinner', name: 'dinner', label: 'Dinner'},
    par: { applyDaily: true, default: 10 },
    made: 2, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18',     
  },
  {
    id: 'item-11',
    name: 'Fried Rice',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-unassigned', name: 'Unassigned', label: 'Unassigned'},
    timeFrame: { id: 'time-unassigned', name: 'unassigned', label: 'Unassigned'},
    par: { applyDaily: true, default: 10 },
    made: 2, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18',     
  },
  {
    id: 'item-13',
    name: 'Takoyaki',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-1', name: 'kitchen-prep', label: 'Kitchen Prep'},
    timeFrame: { id: 'time-unassigned', name: 'unassigned', label: 'Unassigned'},
    par: { applyDaily: true, default: 10 },
    made: 2, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18',     
  },
  {
    id: 'item-14',
    name: 'Fried Kimchi',
    location: { id: 'location-1', name: 'albany', label: 'Albany'},
    active: true,
    count: true,
    station: { id: 'station-2', name: 'sauces', label: 'Saurces'},
    timeFrame: { id: 'time-unassigned', name: 'unassigned', label: 'Unassigned'},
    par: { applyDaily: true, default: 10 },
    made: 2, 
    onHand: {beg: 1, end: 4}, 
    comments: 'Make it good',
    createdDate: '11/23/18',     
  }                 
]